apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
spec:
  template:
    spec:
      containers:
      - name: training
        image: training
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.dev.svc.cluster.local:5000"
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 86400