apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/backend
- ../../base/mlflow
- ../../base/frontend

namespace: dev

configMapGenerator:
- literals:
  - BACKEND_URL=http://backend:8000
  name: frontend-config
- literals:
  - MLFLOW_TRACKING_URI=http://mlflow:5000
  name: backend-config

images:
- name: backend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/backend
  newTag: 0.1.00
- name: frontend
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/frontend
  newTag: 0.0.7
- name: training
  newName: us-central1-docker.pkg.dev/devops-mlops-483223/ml-repo/training
  newTag: 0.0.15
